### ISSUE TITLE
Client side error

### ISSUE THREAD

**Issue by iaroshvictor** [Unforgiven-wanda/electrify-updated-test#7]
Everythink works fine when i run meteor, but when i run electrify, i get a couple of errors that are related to client side 
![capture](https://cloud.githubusercontent.com/assets/25705590/24200058/7c2fdf72-0f14-11e7-8c43-90d53a651ed4.PNG)

**Comment by HZSamir** [comment]
Yep, that is because Meteor does not play well with Materialize. The problem does not come from Electron or Electrify.
I seem to remember there are some possible ways to fix this (Google `Meteor materialize`), or my advice, use www.material-ui.com The components are beautiful and it plays well with Meteor.

**Comment by iaroshvictor** [comment]
Yes, you are absolutely right. Thank you a lot

**Comment by HZSamir** [comment]
Closing then :)
